apiVersion: v1
kind: Pod
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  containers:
  - name: eawangyadb
    image: veawangya/techharbordb
    ports:
    - name: vprodb-port
      containerPort: 3306

    env:
     - name: MYSQL_ROOT_PASSWORD
       value: "eawangyapass"

